version: '3.2'

services:
  postgres:
    image: postgres:9.5.6
    expose:
      - "5432"

  redis:
    image: redis
    expose:
      - "6379"

  nginx:
    build: ./develop/yacs-nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - core

  core:
    build: ./develop/yacs
    environment:
      - RAILS_ENV=development
      - SECRET_KEY_BASE=6ae504547712ae4faf35b9d6186322cf
      - SECRET_TOKEN=cc621dab5bb79f81057a7d17c8ceea42
      - WEB_CONCURRENCY=1
      - MAX_THREADS=2
    ports:
      - "4100:4100"
    volumes:
      - ./develop/yacs:/usr/src/app

  core-consumer:
    build: ./develop/yacs
    environment:
      - RAILS_ENV=development
    volumes:
      - ./develop/yacs:/usr/src/app

  web:
    build: ./develop/yacs-web
    ports:
      - "4200:4200"
    volumes:
      - "./develop/yacs-web/src:/usr/src/app/src"
    command: "ng build --watch"

  # admin:
  #   build: ./develop/yacs-admin
  #   ports:
  #     - "4300:4300"

  users:
    build: ./develop/yacs-users
    ports:
      - "4400:4400"
    volumes:
      - "./develop/yacs-users:/usr/src/app"

  malg:
    build: ./develop/yacs-malg
    ports:
      - "4500:4500"
    volumes:
      - "./develop/yacs-malg:/usr/src/app"

#  kafka-manager:
#    image: sheepkiller/kafka-manager:latest
#    ports:
#      - "9000:9000"
#    links:
#      - zookeeper
#      - kafka
#    environment:
#      ZK_HOSTS: zookeeper:2181
#      KM_ARGS: -Djava.net.preferIPv4Stack=true


  # Planner Stuff!
  planner-web:
    build: ./develop/yacs-prereq-web
    depends_on:
      - planner-data
    ports:
      - "4700:4200"
    volumes:
      - ./develop/yacs-prereq-web/src:/usr/src/app/src
    command: "ng serve --host 0.0.0.0 --disable-host-check"

  planner-data:
    build: ./develop/yacs-prereq-data
    ports:
      - "4600:3100"
    expose:
      - "3100"
